name: release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - 
        name: Build xiaoya-proxy.jar
        id: build_jar
        run: |
          version=$(cat pom.xml | grep -A1 xiaoya_proxy | grep version | perl -pe "s|.*((\d+\.?){3,}).*|\1|")
          echo "XIAOYA_PROXY_VERSION=v${version}" >> $GITHUB_ENV
          mvn clean package

      - 
        name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/xiaoya-proxy
          tags: |
            type=raw,value=${{ env.XIAOYA_PROXY_VERSION }}
            type=raw,value=latest

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v3
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/xiaoya-proxy
          short-description: 小雅Alist的相关周边
          readme-filepath: README.md

      - 
        name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.XIAOYA_PROXY_VERSION }}
          tag_name: ${{ env.XIAOYA_PROXY_VERSION }}
          files: |
            ./target/xiaoya_proxy-*.jar
